openapi: 3.0.0
info:
  title: Simple User Application API
  description: API for a basic user application with login functionality.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /:
    get:
      summary: Home endpoint
      description: Returns a greeting message.
      responses:
        '200':
          description: A simple greeting message
          content:
            text/html:
              schema:
                type: string
                example: Hello, World!

  